### PR TITLE
Just identify the three browser agents

### PR DESCRIPTION
**Pull request by catull**
What is the purpose of calculating exactly which windows browser version is used?
All that matters is WHETHER the browser is a Microsoft one - MSIE, Trident or Edge.
No benefit in knowing more than that.

### CODE REVIEW

**Comment by catull** [comment]
Please explain why in [login.component.ts](https://github.com/TwanoO67/ngx-admin-lte/blob/develop/src/layouts/login/login.component.ts#L16) the call to

```javascript
window.dispatchEvent( new Event( 'resize' ) );
```

is performed unconditionally ?

**Comment by TwanoO67** [comment]
This one is needed because in "most" case, the first resize event is poped before the angular application is loaded.
So the AdminLTE column resizing took place too early.
Resulting in a page that don't take all the size available.

It's difficult to reproduce because it's related to cpu/network performance, but it's appear to be not browser-related, so it's performed unconditionnaly.

**Comment by catull** [comment]
So, the resolution is either

         the code is not changed, but we add specific tests ?
Or
        we simplify the code, add a note that perhaps we have to revisit it.

I am biased, given I have raised this issue with one of the options.

I can live with either one of the options, the current situation is displeasing though.

**Comment by TwanoO67** [comment]
> I have raised this issue with one of the options

What issue ? the column sizing ? 
I though it was fix by the resizing event.
Are you able to reproduce ? On what browser ?

I will merge your proposition for the moment (as it keep the code as a comment).
But we should recreate an issue about that if the case is still happening.

**Comment by catull** [comment]
I agree.

**Pull request merged**
