### PR TITLE
delete box

### PR DESCRIPTION
**Pull request by amehat**

### CODE REVIEW

**Comment by amehat** [comment]
it's a shame, we can not put as many widget as we want for each page.

**Comment by amehat** [comment]
I understand, but in this case, it should have a layout without box and that we can choose this layout or the one already in place.

**Comment by TwanoO67** [comment]
That would be a perfectly fine alternative. we could also provide a parameter in this template to disable that part of the dom, but I'm sure how angular can handle two router-outlet in a component

**Comment by TwanoO67** [comment]
*not sure how...

**Comment by amehat** [comment]
I added a layout "main", we can then choose it in the routes.

**Comment by TwanoO67** [comment]
Hello,
This feature has been added to the new 1.1.0 version.
You can now set the "boxed_style":false option on your layout.
This way it would be simpler to maintain.
Thanks for the idea

**Pull request closed without merging**
